import { Shop, ShopTemplate } from './types';

export const MOCK_SHOPS: Shop[] = [
  {
    id: '1',
    name: "Mary's Electronics Kiosk",
    category: 'Electronics',
    location: { latitude: -1.286389, longitude: 36.817223 },
    distance: '300m Away',
    rating: 4.5,
    image: '/images/optimized/Marys_electronic-1024.webp',
    products: [
      { id: 'p1', name: 'iPhone Charger', price: 1500, stock: 15, category: 'Accessories', image: 'https://images.unsplash.com/photo-1583863762439-9a2469779a83?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p2', name: 'Earphones', price: 800, stock: 5, category: 'Accessories', image: 'https://images.unsplash.com/photo-1606841638048-a428c5a2c26c?q=80&w=1932&auto=format&fit=crop' },
      { id: 'p3', name: 'Power Bank', price: 2500, stock: 10, category: 'Accessories', image: 'https://images.unsplash.com/photo-1588822838380-f35c5c935432?q=80&w=1974&auto=format&fit=crop' },
    ],
  },
  {
    id: '2',
    name: "Juma's Fresh Groceries",
    category: 'Food',
    location: { latitude: -1.2855, longitude: 36.818 },
    distance: '500m Away',
    rating: 4.8,
    image: '/images/optimized/Jumas_fresh-1024.webp',
    products: [
      { id: 'p4', name: 'Tomatoes (kg)', price: 120, stock: 50, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1561136594-7247da06aefb?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p5', name: 'Onions (kg)', price: 100, stock: 60, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1587402922203-b09819df8787?q=80&w=1933&auto=format&fit=crop' },
      { id: 'p6', name: 'Avocado (piece)', price: 30, stock: 100, category: 'Fruits', image: 'https://images.unsplash.com/photo-1522841113583-1b2b3a1e1b1a?q=80&w=1974&auto=format&fit=crop' },
    ],
  },
  {
    id: '3',
    name: 'General Store B',
    category: 'General',
    location: { latitude: -1.287, longitude: 36.816 },
    distance: '450m Away',
    rating: 4.2,
    image: '/images/optimized/General_store_B-1024.webp',
    products: [
      { id: 'p7', name: 'Soap', price: 80, stock: 40, category: 'Toiletries' },
      { id: 'p8', name: 'Cooking Oil (L)', price: 350, stock: 25, category: 'Pantry' },
    ],
  },
  {
    id: '4',
    name: "Ankara Styles by Fenna",
    category: 'General',
    location: { latitude: -1.2848, longitude: 36.8195 },
    distance: '650m Away',
    rating: 4.9,
    image: '/images/optimized/Ankara_styles-1024.webp',
    products: [
      { id: 'p11', name: 'Custom Kitenge Dress', price: 4500, stock: 10, category: 'Apparel' },
      { id: 'p12', name: "Men's Casual Shirt", price: 2500, stock: 20, category: 'Apparel' },
      { id: 'p13', name: 'Ankara Headwrap', price: 800, stock: 30, category: 'Accessories' },
    ],
  },
  {
    id: '5',
    name: "Kazi Moto Boda Repair",
    category: 'Service',
    location: { latitude: -1.2881, longitude: 36.8155 },
    distance: '700m Away',
    rating: 4.6,
    image: '/images/optimized/Kazi_moto-1024.webp',
    products: [
      { id: 's1', name: 'Oil Change', price: 500, stock: 999, category: 'Maintenance' },
      { id: 's2', name: 'Puncture Repair', price: 200, stock: 999, category: 'Tires' },
      { id: 's3', name: 'Brake Pad Replacement', price: 800, stock: 50, category: 'Brakes' },
    ],
  },
  {
    id: '6',
    name: "PesaPoint M-Pesa Agent",
    category: 'Service',
    location: { latitude: -1.2850, longitude: 36.8160 },
    distance: '250m Away',
    rating: 4.7,
    image: '/images/optimized/PesaPoint-1024.webp',
    products: [
      { id: 's6', name: 'Deposit Funds', price: 0, stock: 999, category: 'Transactions' },
      { id: 's7', name: 'Withdraw Funds', price: 0, stock: 999, category: 'Transactions' },
      { id: 's8', name: 'Pay Bill (KPLC, Water)', price: 0, stock: 999, category: 'Bill Payments' },
    ],
  },
  {
    id: '8',
    name: "Mama's Corner Supermarket",
    category: 'Food',
    location: { latitude: -1.2865, longitude: 36.8178 },
    distance: '350m Away',
    rating: 4.4,
    image: '/images/optimized/Mamas_supermarket-1024.webp',
    products: [
      { id: 'p14', name: 'Rice (2kg)', price: 280, stock: 45, category: 'Pantry', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p15', name: 'Cooking Oil (1L)', price: 180, stock: 30, category: 'Pantry', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p16', name: 'Sugar (1kg)', price: 120, stock: 60, category: 'Pantry', image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p17', name: 'Bread Loaf', price: 80, stock: 25, category: 'Bakery', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=2072&auto=format&fit=crop' },
    ],
  },
  {
    id: '9',
    name: "HealthFirst Pharmacy",
    category: 'Service',
    location: { latitude: -1.2858, longitude: 36.8188 },
    distance: '420m Away',
    rating: 4.6,
    image: '/images/optimized/Healthfirst-1024.webp',
    products: [
      { id: 's16', name: 'Paracetamol (20 tablets)', price: 50, stock: 100, category: 'Medicines' },
      { id: 's17', name: 'Bandages (pack)', price: 120, stock: 80, category: 'First Aid' },
      { id: 's18', name: 'Vitamin C Tablets', price: 350, stock: 40, category: 'Supplements' },
      { id: 's19', name: 'Blood Pressure Check', price: 200, stock: 999, category: 'Health Services' },
    ],
  },
  {
    id: '10',
    name: "BuildRight Hardware",
    category: 'General',
    location: { latitude: -1.2878, longitude: 36.8158 },
    distance: '580m Away',
    rating: 4.3,
    image: '/images/optimized/Buildright-1024.webp',
    products: [
      { id: 'p18', name: 'Hammer', price: 450, stock: 15, category: 'Tools' },
      { id: 'p19', name: 'Screwdriver Set', price: 320, stock: 20, category: 'Tools' },
      { id: 'p20', name: 'Paint Brush (2")', price: 80, stock: 35, category: 'Painting' },
      { id: 'p21', name: 'Electrical Wire (per meter)', price: 25, stock: 200, category: 'Electrical' },
    ],
  },
  {
    id: '11',
    name: "Corner Cafe & Restaurant",
    category: 'Food',
    location: { latitude: -1.2845, longitude: 36.8198 },
    distance: '720m Away',
    rating: 4.7,
    image: '/images/optimized/Corner_cafe-1024.webp',
    products: [
      { id: 'f1', name: 'Chapati & Beans', price: 150, stock: 999, category: 'Meals' },
      { id: 'f2', name: 'Black Coffee', price: 80, stock: 999, category: 'Beverages' },
      { id: 'f3', name: 'Fresh Juice (Pineapple)', price: 120, stock: 999, category: 'Beverages' },
      { id: 'f4', name: 'Mandazi (2 pieces)', price: 40, stock: 999, category: 'Snacks' },
    ],
  },
  {
    id: '12',
    name: "Glow Beauty Salon",
    category: 'Service',
    location: { latitude: -1.2885, longitude: 36.8165 },
    distance: '650m Away',
    rating: 4.8,
    image: '/images/optimized/Glow_Beauty-1024.webp',
    products: [
      { id: 's20', name: 'Hair Braiding (Full Head)', price: 800, stock: 999, category: 'Hair' },
      { id: 's21', name: 'Facial Treatment', price: 600, stock: 999, category: 'Skin Care' },
      { id: 's22', name: 'Manicure & Pedicure', price: 400, stock: 999, category: 'Nails' },
      { id: 's23', name: 'Eyebrow Threading', price: 150, stock: 999, category: 'Grooming' },
    ],
  },
  {
    id: '13',
    name: "QuickWash Laundry",
    category: 'Service',
    location: { latitude: -1.2862, longitude: 36.8175 },
    distance: '380m Away',
    rating: 4.5,
    image: '/images/optimized/QuickWash-1024.webp',
    products: [
      { id: 's24', name: 'Wash & Fold (per kg)', price: 50, stock: 999, category: 'Laundry' },
      { id: 's25', name: 'Dry Cleaning (shirt)', price: 200, stock: 999, category: 'Dry Cleaning' },
      { id: 's26', name: 'Ironing Service (per piece)', price: 30, stock: 999, category: 'Ironing' },
      { id: 's27', name: 'Same Day Service', price: 100, stock: 999, category: 'Express' },
    ],
  },
  {
    id: '14',
    name: "Knowledge Hub Bookstore",
    category: 'General',
    location: { latitude: -1.2852, longitude: 36.8182 },
    distance: '480m Away',
    rating: 4.6,
    image: '/images/optimized/Knowledge_hub-1024.webp',
    products: [
      { id: 'p22', name: 'Primary School Exercise Book', price: 25, stock: 150, category: 'Stationery' },
      { id: 'p23', name: 'Ballpoint Pen (pack of 10)', price: 80, stock: 80, category: 'Stationery' },
      { id: 'p24', name: 'Mathematics Textbook', price: 450, stock: 20, category: 'Books' },
      { id: 'p25', name: 'Coloring Pencils (12 pack)', price: 120, stock: 40, category: 'Art Supplies' },
    ],
  },
  {
    id: '15',
    name: "StepIn Shoe Repair",
    category: 'Service',
    location: { latitude: -1.2872, longitude: 36.8152 },
    distance: '520m Away',
    rating: 4.4,
    image: '/images/optimized/StepIn_shoe-1024.webp',
    products: [
      { id: 's28', name: 'Sole Replacement', price: 300, stock: 999, category: 'Repairs' },
      { id: 's29', name: 'Heel Repair', price: 150, stock: 999, category: 'Repairs' },
      { id: 's30', name: 'Shoe Polish', price: 100, stock: 999, category: 'Cleaning' },
      { id: 's31', name: 'Key Cutting', price: 50, stock: 999, category: 'Keys' },
    ],
  },
  {
    id: '16',
    name: "TechHub Computer Services",
    category: 'Service',
    location: { latitude: -1.2842, longitude: 36.8202 },
    distance: '780m Away',
    rating: 4.7,
    image: '/images/optimized/TechHub-1024.webp',
    products: [
      { id: 's32', name: 'Computer Repair', price: 500, stock: 999, category: 'Repairs' },
      { id: 's33', name: 'Virus Removal', price: 300, stock: 999, category: 'Security' },
      { id: 's34', name: 'Data Recovery', price: 800, stock: 999, category: 'Data' },
      { id: 's35', name: 'Printer Setup', price: 200, stock: 999, category: 'Setup' },
    ],
  },
  {
    id: '17',
    name: "GreenThumb Nursery",
    category: 'General',
    location: { latitude: -1.2888, longitude: 36.8172 },
    distance: '690m Away',
    rating: 4.5,
    image: '/images/optimized/Greenthumb-1024.webp',
    products: [
      { id: 'p26', name: 'Rose Plant', price: 250, stock: 30, category: 'Plants' },
      { id: 'p27', name: 'Fertilizer (1kg)', price: 180, stock: 50, category: 'Gardening' },
      { id: 'p28', name: 'Garden Hose (5m)', price: 350, stock: 15, category: 'Tools' },
      { id: 'p29', name: 'Potting Soil (5kg)', price: 120, stock: 40, category: 'Soil' },
    ],
  },
];

export const SHOP_TEMPLATES: ShopTemplate[] = [
    {
        name: "Electronics Kiosk",
        category: 'Electronics',
        image: '/images/optimized/Marys_electronic-1024.webp',
        description: 'A fully-stocked kiosk with the latest mobile accessories and gadgets.',
        products: [
            { id: 'p1', name: 'iPhone Charger', price: 1500, stock: 15, category: 'Accessories', image: 'https://images.unsplash.com/photo-1583863762439-9a2469779a83?q=80&w=2070&auto=format&fit=crop' },
            { id: 'p2', name: 'Earphones', price: 800, stock: 5, category: 'Accessories', image: 'https://images.unsplash.com/photo-1606841638048-a428c5a2c26c?q=80&w=1932&auto=format&fit=crop' },
            { id: 'p3', name: 'Power Bank', price: 2500, stock: 10, category: 'Accessories', image: 'https://images.unsplash.com/photo-1588822838380-f35c5c935432?q=80&w=1974&auto=format&fit=crop' },
            { id: 'p4', name: 'Screen Protector', price: 500, stock: 30, category: 'Accessories' },
            { id: 'p5', name: 'USB-C Cable', price: 700, stock: 25, category: 'Accessories' },
        ],
    },
    {
        name: "Fresh Grocery Store",
        category: 'Food',
        image: '/images/optimized/Jumas_fresh-1024.webp',
        description: 'Your neighborhood source for fresh, locally-sourced fruits and vegetables.',
        products: [
            { id: 'p6', name: 'Tomatoes (kg)', price: 120, stock: 50, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1561136594-7247da06aefb?q=80&w=2070&auto=format&fit=crop' },
            { id: 'p7', name: 'Onions (kg)', price: 100, stock: 60, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1587402922203-b09819df8787?q=80&w=1933&auto=format&fit=crop' },
            { id: 'p8', name: 'Avocado (piece)', price: 30, stock: 100, category: 'Fruits', image: 'https://images.unsplash.com/photo-1522841113583-1b2b3a1e1b1a?q=80&w=1974&auto=format&fit=crop' },
            { id: 'p9', name: 'Bananas (bunch)', price: 50, stock: 80, category: 'Fruits' },
            { id: 'p10', name: 'Spinach (bunch)', price: 40, stock: 40, category: 'Vegetables' },
        ],
    },
    {
        name: "Ankara Styles by Fenna",
        category: 'General',
        image: '/images/optimized/Ankara_styles-1024.webp',
        description: 'Custom-made ankara outfits, dresses, and accessories for all occasions.',
        products: [
            { id: 'p11', name: 'Custom Kitenge Dress', price: 4500, stock: 10, category: 'Apparel' },
            { id: 'p12', name: "Men's Casual Shirt", price: 2500, stock: 20, category: 'Apparel' },
            { id: 'p13', name: 'Ankara Headwrap', price: 800, stock: 30, category: 'Accessories' },
            { id: 'p14', name: 'Matching Bag', price: 1800, stock: 15, category: 'Accessories' },
            { id: 'p15', name: 'Fabric (per meter)', price: 600, stock: 100, category: 'Materials' },
        ],
    },
    {
        name: "Kazi Moto Boda Repair",
        category: 'Service',
        image: '/images/optimized/Kazi_moto-1024.webp',
        description: 'Fast and reliable repairs for all motorbike models. Oil changes, tire punctures, and engine checks.',
        products: [
            { id: 's1', name: 'Oil Change', price: 500, stock: 999, category: 'Maintenance' },
            { id: 's2', name: 'Puncture Repair', price: 200, stock: 999, category: 'Tires' },
            { id: 's3', name: 'Brake Pad Replacement', price: 800, stock: 50, category: 'Brakes' },
            { id: 's4', name: 'Full Engine Service', price: 3000, stock: 999, category: 'Engine' },
            { id: 's5', name: 'Chain Lubrication', price: 150, stock: 999, category: 'Maintenance' },
        ],
    },
    {
        name: "PesaPoint M-Pesa",
        category: 'Service',
        image: '/images/optimized/PesaPoint-1024.webp',
        description: 'Your convenient spot for M-Pesa deposits, withdrawals, and bill payments.',
        products: [
            { id: 's6', name: 'Deposit Funds', price: 0, stock: 999, category: 'Transactions' },
            { id: 's7', name: 'Withdraw Funds', price: 0, stock: 999, category: 'Transactions' },
            { id: 's8', name: 'Pay Bill (KPLC, Water)', price: 0, stock: 999, category: 'Bill Payments' },
            { id: 's9', name: 'Buy Airtime (Safaricom)', price: 0, stock: 999, category: 'Airtime' },
            { id: 's10', name: 'SIM Card Registration', price: 50, stock: 100, category: 'Services' },
        ],
    },
    {
        name: "Fresh Cuts Barbershop",
        category: 'Service',
        image: '/images/optimized/Fresh_cuts-1024.webp',
        description: 'Sharp haircuts, clean shaves, and professional grooming for the modern gentleman.',
        products: [
            { id: 's11', name: 'Standard Haircut', price: 300, stock: 999, category: 'Hair' },
            { id: 's12', name: 'Beard Trim & Shape-up', price: 200, stock: 999, category: 'Grooming' },
            { id: 's13', name: 'Hot Towel Shave', price: 400, stock: 999, category: 'Grooming' },
            { id: 's14', name: "Kids' Cut (Under 12)", price: 250, stock: 999, category: 'Hair' },
            { id: 's15', name: 'Hair Wash & Style', price: 150, stock: 999, category: 'Hair' },
        ],
    },
    {
        name: "Corner Supermarket",
        category: 'Food',
        image: '/images/optimized/Mamas_supermarket-1024.webp',
        description: 'Your neighborhood supermarket with fresh groceries, pantry essentials, and daily needs.',
        products: [
            { id: 'p14', name: 'Rice (2kg)', price: 280, stock: 45, category: 'Pantry' },
            { id: 'p15', name: 'Cooking Oil (1L)', price: 180, stock: 30, category: 'Pantry' },
            { id: 'p16', name: 'Sugar (1kg)', price: 120, stock: 60, category: 'Pantry' },
            { id: 'p17', name: 'Bread Loaf', price: 80, stock: 25, category: 'Bakery' },
            { id: 'p18', name: 'Milk (1L)', price: 90, stock: 35, category: 'Dairy' },
        ],
    },
    {
        name: "Community Pharmacy",
        category: 'Service',
        image: '/images/optimized/Healthfirst-1024.webp',
        description: 'Your trusted source for medicines, health supplements, and basic healthcare services.',
        products: [
            { id: 's16', name: 'Paracetamol (20 tablets)', price: 50, stock: 100, category: 'Medicines' },
            { id: 's17', name: 'Bandages (pack)', price: 120, stock: 80, category: 'First Aid' },
            { id: 's18', name: 'Vitamin C Tablets', price: 350, stock: 40, category: 'Supplements' },
            { id: 's19', name: 'Blood Pressure Check', price: 200, stock: 999, category: 'Health Services' },
            { id: 's20', name: 'Consultation', price: 300, stock: 999, category: 'Health Services' },
        ],
    },
    {
        name: "Hardware Store",
        category: 'General',
        image: '/images/optimized/Buildright-1024.webp',
        description: 'Tools, building materials, and home improvement supplies for all your DIY projects.',
        products: [
            { id: 'p19', name: 'Hammer', price: 450, stock: 15, category: 'Tools' },
            { id: 'p20', name: 'Screwdriver Set', price: 320, stock: 20, category: 'Tools' },
            { id: 'p21', name: 'Paint Brush (2")', price: 80, stock: 35, category: 'Painting' },
            { id: 'p22', name: 'Electrical Wire (per meter)', price: 25, stock: 200, category: 'Electrical' },
            { id: 'p23', name: 'Pipe Wrench', price: 380, stock: 12, category: 'Plumbing' },
        ],
    },
    {
        name: "Local Cafe",
        category: 'Food',
        image: '/images/optimized/Corner_cafe-1024.webp',
        description: 'Freshly prepared meals, hot beverages, and quick bites for busy days.',
        products: [
            { id: 'f1', name: 'Chapati & Beans', price: 150, stock: 999, category: 'Meals' },
            { id: 'f2', name: 'Black Coffee', price: 80, stock: 999, category: 'Beverages' },
            { id: 'f3', name: 'Fresh Juice (Pineapple)', price: 120, stock: 999, category: 'Beverages' },
            { id: 'f4', name: 'Mandazi (2 pieces)', price: 40, stock: 999, category: 'Snacks' },
            { id: 'f5', name: 'Tea with Milk', price: 60, stock: 999, category: 'Beverages' },
        ],
    },
    {
        name: "Beauty Salon",
        category: 'Service',
        image: '/images/optimized/Glow_Beauty-1024.webp',
        description: 'Professional hair styling, beauty treatments, and grooming services.',
        products: [
            { id: 's21', name: 'Hair Braiding (Full Head)', price: 800, stock: 999, category: 'Hair' },
            { id: 's22', name: 'Facial Treatment', price: 600, stock: 999, category: 'Skin Care' },
            { id: 's23', name: 'Manicure & Pedicure', price: 400, stock: 999, category: 'Nails' },
            { id: 's24', name: 'Eyebrow Threading', price: 150, stock: 999, category: 'Grooming' },
            { id: 's25', name: 'Hair Coloring', price: 500, stock: 999, category: 'Hair' },
        ],
    },
    {
        name: "Laundry Service",
        category: 'Service',
        image: '/images/optimized/QuickWash-1024.webp',
        description: 'Professional laundry, dry cleaning, and ironing services for your busy lifestyle.',
        products: [
            { id: 's26', name: 'Wash & Fold (per kg)', price: 50, stock: 999, category: 'Laundry' },
            { id: 's27', name: 'Dry Cleaning (shirt)', price: 200, stock: 999, category: 'Dry Cleaning' },
            { id: 's28', name: 'Ironing Service (per piece)', price: 30, stock: 999, category: 'Ironing' },
            { id: 's29', name: 'Same Day Service', price: 100, stock: 999, category: 'Express' },
            { id: 's30', name: 'Curtain Cleaning', price: 150, stock: 999, category: 'Special Care' },
        ],
    },
];