import { Shop, ShopTemplate } from './types';

export const MOCK_SHOPS: Shop[] = [
  {
    id: '1',
    name: "Mary's Electronics Kiosk",
    category: 'Electronics',
    location: { latitude: -1.286389, longitude: 36.817223 },
    distance: '300m Away',
    rating: 4.5,
    image: '/images/optimized/Marys_electronic-1024.webp',
    products: [
      { id: 'p1', name: 'iPhone Charger', price: 1500, stock: 15, category: 'Accessories', image: 'https://images.unsplash.com/photo-1583863762439-9a2469779a83?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p2', name: 'Earphones', price: 800, stock: 5, category: 'Accessories', image: 'https://images.unsplash.com/photo-1606841638048-a428c5a2c26c?q=80&w=1932&auto=format&fit=crop' },
      { id: 'p3', name: 'Power Bank', price: 2500, stock: 10, category: 'Accessories', image: 'https://images.unsplash.com/photo-1588822838380-f35c5c935432?q=80&w=1974&auto=format&fit=crop' },
    ],
  },
  {
    id: '2',
    name: "Juma's Fresh Groceries",
    category: 'Food',
    location: { latitude: -1.2855, longitude: 36.818 },
    distance: '500m Away',
    rating: 4.8,
    image: '/images/optimized/Jumas_fresh-1024.webp',
    products: [
      { id: 'p4', name: 'Tomatoes (kg)', price: 120, stock: 50, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1561136594-7247da06aefb?q=80&w=2070&auto=format&fit=crop' },
      { id: 'p5', name: 'Onions (kg)', price: 100, stock: 60, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1587402922203-b09819df8787?q=80&w=1933&auto=format&fit=crop' },
      { id: 'p6', name: 'Avocado (piece)', price: 30, stock: 100, category: 'Fruits', image: 'https://images.unsplash.com/photo-1522841113583-1b2b3a1e1b1a?q=80&w=1974&auto=format&fit=crop' },
    ],
  },
  {
    id: '3',
    name: 'General Store B',
    category: 'General',
    location: { latitude: -1.287, longitude: 36.816 },
    distance: '450m Away',
    rating: 4.2,
    image: '/images/optimized/General_store_B-1024.webp',
    products: [
      { id: 'p7', name: 'Soap', price: 80, stock: 40, category: 'Toiletries' },
      { id: 'p8', name: 'Cooking Oil (L)', price: 350, stock: 25, category: 'Pantry' },
    ],
  },
  {
    id: '4',
    name: "Ankara Styles by Fenna",
    category: 'General',
    location: { latitude: -1.2848, longitude: 36.8195 },
    distance: '650m Away',
    rating: 4.9,
    image: '/images/optimized/Ankara_styles-1024.webp',
    products: [
      { id: 'p11', name: 'Custom Kitenge Dress', price: 4500, stock: 10, category: 'Apparel' },
      { id: 'p12', name: "Men's Casual Shirt", price: 2500, stock: 20, category: 'Apparel' },
      { id: 'p13', name: 'Ankara Headwrap', price: 800, stock: 30, category: 'Accessories' },
    ],
  },
  {
    id: '5',
    name: "Kazi Moto Boda Repair",
    category: 'Service',
    location: { latitude: -1.2881, longitude: 36.8155 },
    distance: '700m Away',
    rating: 4.6,
    image: '/images/optimized/Kazi_moto-1024.webp',
    products: [
      { id: 's1', name: 'Oil Change', price: 500, stock: 999, category: 'Maintenance' },
      { id: 's2', name: 'Puncture Repair', price: 200, stock: 999, category: 'Tires' },
      { id: 's3', name: 'Brake Pad Replacement', price: 800, stock: 50, category: 'Brakes' },
    ],
  },
  {
    id: '6',
    name: "PesaPoint M-Pesa Agent",
    category: 'Service',
    location: { latitude: -1.2850, longitude: 36.8160 },
    distance: '250m Away',
    rating: 4.7,
    image: '/images/optimized/PesaPoint-1024.webp',
    products: [
      { id: 's6', name: 'Deposit Funds', price: 0, stock: 999, category: 'Transactions' },
      { id: 's7', name: 'Withdraw Funds', price: 0, stock: 999, category: 'Transactions' },
      { id: 's8', name: 'Pay Bill (KPLC, Water)', price: 0, stock: 999, category: 'Bill Payments' },
    ],
  },
  {
    id: '7',
    name: "Fresh Cuts Barbershop",
    category: 'Service',
    location: { latitude: -1.2875, longitude: 36.8185 },
    distance: '800m Away',
    rating: 4.8,
    image: '/images/optimized/Fresh_cuts-1024.webp',
    products: [
      { id: 's11', name: 'Standard Haircut', price: 300, stock: 999, category: 'Hair' },
      { id: 's12', name: 'Beard Trim & Shape-up', price: 200, stock: 999, category: 'Grooming' },
      { id: 's13', name: 'Hot Towel Shave', price: 400, stock: 999, category: 'Grooming' },
    ],
  },
];

export const SHOP_TEMPLATES: ShopTemplate[] = [
    {
        name: "Electronics Kiosk",
        category: 'Electronics',
        image: '/images/optimized/Marys_electronic-1024.webp',
        description: 'A fully-stocked kiosk with the latest mobile accessories and gadgets.',
        products: [
            { id: 'p1', name: 'iPhone Charger', price: 1500, stock: 15, category: 'Accessories', image: 'https://images.unsplash.com/photo-1583863762439-9a2469779a83?q=80&w=2070&auto=format&fit=crop' },
            { id: 'p2', name: 'Earphones', price: 800, stock: 5, category: 'Accessories', image: 'https://images.unsplash.com/photo-1606841638048-a428c5a2c26c?q=80&w=1932&auto=format&fit=crop' },
            { id: 'p3', name: 'Power Bank', price: 2500, stock: 10, category: 'Accessories', image: 'https://images.unsplash.com/photo-1588822838380-f35c5c935432?q=80&w=1974&auto=format&fit=crop' },
            { id: 'p4', name: 'Screen Protector', price: 500, stock: 30, category: 'Accessories' },
            { id: 'p5', name: 'USB-C Cable', price: 700, stock: 25, category: 'Accessories' },
        ],
    },
    {
        name: "Fresh Grocery Store",
        category: 'Food',
        image: '/images/optimized/Jumas_fresh-1024.webp',
        description: 'Your neighborhood source for fresh, locally-sourced fruits and vegetables.',
        products: [
            { id: 'p6', name: 'Tomatoes (kg)', price: 120, stock: 50, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1561136594-7247da06aefb?q=80&w=2070&auto=format&fit=crop' },
            { id: 'p7', name: 'Onions (kg)', price: 100, stock: 60, category: 'Vegetables', image: 'https://images.unsplash.com/photo-1587402922203-b09819df8787?q=80&w=1933&auto=format&fit=crop' },
            { id: 'p8', name: 'Avocado (piece)', price: 30, stock: 100, category: 'Fruits', image: 'https://images.unsplash.com/photo-1522841113583-1b2b3a1e1b1a?q=80&w=1974&auto=format&fit=crop' },
            { id: 'p9', name: 'Bananas (bunch)', price: 50, stock: 80, category: 'Fruits' },
            { id: 'p10', name: 'Spinach (bunch)', price: 40, stock: 40, category: 'Vegetables' },
        ],
    },
    {
        name: "Ankara Styles by Fenna",
        category: 'General',
        image: '/images/optimized/Ankara_styles-1024.webp',
        description: 'Custom-made ankara outfits, dresses, and accessories for all occasions.',
        products: [
            { id: 'p11', name: 'Custom Kitenge Dress', price: 4500, stock: 10, category: 'Apparel' },
            { id: 'p12', name: "Men's Casual Shirt", price: 2500, stock: 20, category: 'Apparel' },
            { id: 'p13', name: 'Ankara Headwrap', price: 800, stock: 30, category: 'Accessories' },
            { id: 'p14', name: 'Matching Bag', price: 1800, stock: 15, category: 'Accessories' },
            { id: 'p15', name: 'Fabric (per meter)', price: 600, stock: 100, category: 'Materials' },
        ],
    },
    {
        name: "Kazi Moto Boda Repair",
        category: 'Service',
        image: '/images/optimized/Kazi_moto-1024.webp',
        description: 'Fast and reliable repairs for all motorbike models. Oil changes, tire punctures, and engine checks.',
        products: [
            { id: 's1', name: 'Oil Change', price: 500, stock: 999, category: 'Maintenance' },
            { id: 's2', name: 'Puncture Repair', price: 200, stock: 999, category: 'Tires' },
            { id: 's3', name: 'Brake Pad Replacement', price: 800, stock: 50, category: 'Brakes' },
            { id: 's4', name: 'Full Engine Service', price: 3000, stock: 999, category: 'Engine' },
            { id: 's5', name: 'Chain Lubrication', price: 150, stock: 999, category: 'Maintenance' },
        ],
    },
    {
        name: "PesaPoint M-Pesa",
        category: 'Service',
        image: '/images/optimized/PesaPoint-1024.webp',
        description: 'Your convenient spot for M-Pesa deposits, withdrawals, and bill payments.',
        products: [
            { id: 's6', name: 'Deposit Funds', price: 0, stock: 999, category: 'Transactions' },
            { id: 's7', name: 'Withdraw Funds', price: 0, stock: 999, category: 'Transactions' },
            { id: 's8', name: 'Pay Bill (KPLC, Water)', price: 0, stock: 999, category: 'Bill Payments' },
            { id: 's9', name: 'Buy Airtime (Safaricom)', price: 0, stock: 999, category: 'Airtime' },
            { id: 's10', name: 'SIM Card Registration', price: 50, stock: 100, category: 'Services' },
        ],
    },
    {
        name: "Fresh Cuts Barbershop",
        category: 'Service',
        image: '/images/optimized/Fresh_cuts-1024.webp',
        description: 'Sharp haircuts, clean shaves, and professional grooming for the modern gentleman.',
        products: [
            { id: 's11', name: 'Standard Haircut', price: 300, stock: 999, category: 'Hair' },
            { id: 's12', name: 'Beard Trim & Shape-up', price: 200, stock: 999, category: 'Grooming' },
            { id: 's13', name: 'Hot Towel Shave', price: 400, stock: 999, category: 'Grooming' },
            { id: 's14', name: "Kids' Cut (Under 12)", price: 250, stock: 999, category: 'Hair' },
            { id: 's15', name: 'Hair Wash & Style', price: 150, stock: 999, category: 'Hair' },
        ],
    },
];